### ISSUE TITLE
S20+ 64MP Camera Sensor Not Working

### ISSUE THREAD

**Issue by artivity** [Linux4/lineage_OTA#1]
If it's not possible to get it working on this ROM for whatever reason, could you please state it at the top of your description on here and XDA, so that people don't waste their time installing, unless they don't intend to take photos?

👍

**Comment by Linux4** [comment]
This should go to https://github.com/Exynoobs/lineage_OTA
The repo here is only for my builds for gta4xl*.
Also why not report it on xda?
