### ISSUE TITLE
Moin :-)

### ISSUE THREAD

**Issue by note10u** [Linux4/lineage_OTA#4]
Hey , 

erstmal großartige Arbeit von dir - THX 

Hast du zufällig Discord ?

Habe da ne Frage wegen dem Akku Vebrauch beim Galaxy Note 10 + / ds2 

Discord: crackheadone#2928

Grüße gehen raus

**Comment by Linux4** [comment]
Du kannst gerne meiner Telegram Support Gruppe beitreten: https://t.me/exynos9820oss (Englisch)
