### ISSUE TITLE
Very visible stylus lag in most programs

### ISSUE THREAD

**Issue by Splashyn** [Linux4/lineage_OTA#6]
Since at least the last two releases, i experience very heavy lag (up to 2-3cm) with my S pen.
Ive tested this with Squid, OneNote, Sketchbook and Samsung Notes.
I cant find anything in regards to this online, so i am assuming it is a problem with this ROM.

My next step would be to reflash LOS19.0, and then 18.1 to compare.

**Comment by Linux4** [comment]
I'm not going to take any "lag" bug reports this early on 19.0 bringup, sorry.
