### ISSUE TITLE
Emojis not Updating System-Wide

### ISSUE THREAD

**Issue by brxken128** [Linux4/lineage_OTA#7]
I've replaced the `/system/fonts/NotoColorEmoji.ttf` and ensured they're `chmod 644` with a ttf pulled from a spare Samsung device of mine (as I prefer those emojis), but they haven't and won't seem to update. 

I've cleared system cache, I've tried a different ttf file, I'm at my wits' end here. I use Gboard if that seems to change anything, but even in apps such as signal the emojis are still shown as the stock AOSP ones.

This is using the latest beyond2lte LineageOS19 build.

Thank you for creating and maintaining this amazing ROM by the way.

**Comment by Linux4** [comment]
This is neither device specific nor a bug after all,
iirc there were some changes how fonts are handled on Q and up, I'd suggest you looking at some magisk modules supporting Q+ doing something similar
