### ISSUE TITLE
Long Press Power Button for Torch

### ISSUE THREAD

**Issue by brxken128** [Linux4/lineage_OTA#8]
The long press power button to enable the torch seems to be broken.

I'm on beyond2lte, and on the update released today (15th Jan).

Steps to replicate:
- Fully turn the screen off (press the power button)
- Hold the power button

![IMG_20220115_171716.jpg](https://user-images.githubusercontent.com/77554505/149631191-ebd62a6d-05f5-4ba0-a330-e4ab0f2afc4d.jpg)

**Comment by Linux4** [comment]
19.0 isn't anywhere close being completely done, this is just another feature that isn't wired up at all yet.
In general things like that are unlikely to be device specific anyway.
